---

- name: Install nginx
  yum:
    name: nginx
    state: latest
  notify:
    - Restart nginx

- name: Ensure nginx starts at boot time
  service:
    name: nginx
    enabled: yes

- name: Create nginx SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Generate self-signed SSL certificate
  command: >
    openssl req -new -nodes -x509 -days 3650 -extensions v3_ca
      -subj "/C=GB/ST=Oxfordshire/L=Didcot/O=JASMIN/OU=Cluster-as-a-Service/CN=*"
      -keyout /etc/nginx/ssl/awx.key
      -out /etc/nginx/ssl/awx.crt
  args:
    creates: /etc/nginx/ssl/awx.crt
  when: ssl_certificate is not defined
  notify:
    - Restart nginx

- name: Install SSL certificate
  copy:
    content: "{{ ssl_certificate }}"
    dest: /etc/nginx/ssl/awx.crt
  when: ssl_certificate is defined
  notify:
    - Restart nginx

- name: Install SSL private key
  copy:
    content: "{{ ssl_private_key }}"
    dest: /etc/nginx/ssl/awx.key
  when: ssl_certificate is defined
  notify:
    - Restart nginx

- name: Make SSL cert files readable by root only
  file:
    path: "{{ item }}"
    mode: "u=r,g=,o="
  with_items:
    - /etc/nginx/ssl/awx.crt
    - /etc/nginx/ssl/awx.key

- name: Install main nginx configuration
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Remove default site configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - Restart nginx

- name: Install AWX site configuration
  template:
    src: templates/awx.conf
    dest: /etc/nginx/conf.d/awx.conf
  notify:
    - Restart nginx

- name: Allow external HTTP(S) traffic
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
